// <auto-generated />
using InstaFit.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstaFit.Migrations
{
    [DbContext(typeof(InstaDbContext))]
    partial class InstaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstaFit.Models.FitnessPost", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Location");

                    b.Property<string>("URL");

                    b.HasKey("ID");

                    b.ToTable("FitnessPosts");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "This was an exhausting crossFit Workout, EMOM every minute on the minute 10 burpees 1 power clean @75%",
                            Location = "Seattle Crossfit-321 Denny Way",
                            URL = "crossfit.jpeg"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Following the roots of the great Arnold doing these 3 shoulder exercises will get you there!",
                            Location = "Golds Gym-Venice Beach",
                            URL = "Bodybuilding.jpeg"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Playing tennis every sunday has kept me lean and mean",
                            Location = "Tennis courts of charleston- charleston SC",
                            URL = "Tennis.jpeg"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Starting my new journey into weight loss today- lets battle these heart conditions!!",
                            Location = "Anytime FItness- Oralndo, Fla",
                            URL = "Transformation.jpeg"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
